language: cpp
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get update
  - sudo apt-get install libevent-dev
script:
  - make CXX=$CXX CC=$CC CFLAGS=-Werror
  - make test CXX=$CXX CC=$CC CFLAGS=-Werror
