language: cpp
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get update
  - sudo apt-get install libevent-dev liblzma-dev
script:
  - ./configure ${CONFIGURE_ARGS}
  - make CXX=$CXX CC=$CC CXXFLAGS=-Werror
  - make test CXX=$CXX CC=$CC CXXFLAGS=-Werror
env:
  matrix:
  - CONFIGURE_ARGS=--enable-all
  - CONFIGURE_ARGS=--disable-all
  - CONFIGURE_ARGS=--disable-postgres
  - CONFIGURE_ARGS=--disable-lzma
  - CONFIGURE_ARGS=--disable-zlib
  - CONFIGURE_ARGS=
